name: Go

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: build sort
      run: go build -v ./sort.go
    - name: check sort
      run: go vet -n -x ./sort.go
    - name: build searchSimple
      run: go build -v ./searchSimple.go
    - name: check searchSimple
      run: go vet -n -x ./searchSimple.go
    - name: build fibonacci
      run: go build -v ./fibonacci.go
    - name: check fibonacci
      run: go vet -n -x ./fibonacci.go
    - name: build calc
      run: go build -v ./calc.go
    - name: check calc
      run: go vet -n -x ./calc.go
    - name: test
      run: ls *.go | xargs -I {} go vet -x -n {}
#  super-lint:
#    name: Lint source code
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Run Super-Linter
#        uses: github/super-linter@v3
#        env:
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          VALIDATE_GO: true
